version: 2
jobs:
  build:
    docker:
      - image: 'cimg/node:lts'
    steps:
      - checkout

      - run: npm ci

      - run: npm run lint

      - run: npm run checkjs

      - run: npm run test

      - run:
          name: release
          command: npm run semantic-release || true
